In [2]:
import numpy as np
#create a simple matrix
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
U,S,VT = np.linalg.svd(X)
#choose the number of components to keep (e.g.,2)
n_components = 2
# reconstruct the matrix with reduced diamentins
X_reconstructed = np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("orginal matrix:")
print(X)
print("\n reconstructed matrix (with reduced dimentions):")
print(X_reconstructed)


orginal matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 reconstructed matrix (with reduced dimentions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
