In [3]:
import numpy as np
# create matrices
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#addition
C=A+B
#substractiom
D=A-B
#multiplication
E=A*B
#matrix multiplication
F=np.dot(A,B)#or A@B
#TRANSPOSE
A_transpose = A.T
print("addition:")
print(C)
print ("\n substraction")
print(D)
print("\n elementwise multiplication")
print(E)
print("\nmatrix multiplication")
print(F)
print("\n TRANSPOSE;")
print(A_transpose)

addition:
[[ 6  8]
 [10 12]]

 substraction
[[-4 -4]
 [-4 -4]]

 elementwise multiplication
[[ 5 12]
 [21 32]]

matrix multiplication
[[19 22]
 [43 50]]

 TRANSPOSE;
[[1 3]
 [2 4]]
